//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachlor_Essay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historic_NSE_Date
    {
        public int PK { get; set; }
        public string Ticker { get; set; }
        public Nullable<System.DateTime> Date_of_Price { get; set; }
        public Nullable<double> Open_Price { get; set; }
        public Nullable<double> Close_Price { get; set; }
        public Nullable<double> percent_change { get; set; }
        public Nullable<double> Volume { get; set; }
    }
}
