//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachlor_Essay
{
    using System;
    using System.Collections.Generic;
    
    public partial class India_GDP
    {
        public int PK { get; set; }
        public Nullable<System.DateTime> Date_of_GDP { get; set; }
        public Nullable<double> GDP { get; set; }
    }
}
