//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachlor_Essay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bachlor_EssayEntities : DbContext
    {
        public Bachlor_EssayEntities()
            : base("name=Bachlor_EssayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Historic_NSE_Date> Historic_NSE_Date { get; set; }
        public virtual DbSet<India_GDP> India_GDP { get; set; }
        public virtual DbSet<MACD> MACDs { get; set; }
        public virtual DbSet<RSI> RSIs { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<US_Yield> US_Yield { get; set; }
    }
}
