//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachlor_Essay
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSI
    {
        public int pk { get; set; }
        public string ticker { get; set; }
        public Nullable<System.DateTime> date_t { get; set; }
        public Nullable<double> RSI1 { get; set; }
    }
}
