//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachlor_Essay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string company { get; set; }
        public string ticker { get; set; }
        public Nullable<int> shares { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public Nullable<decimal> current_price { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<decimal> unrealized { get; set; }
    }
}
