//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachlor_Essay
{
    using System;
    using System.Collections.Generic;
    
    public partial class US_Yield
    {
        public int PK { get; set; }
        public Nullable<System.DateTime> Date_of_Bond { get; set; }
        public Nullable<double> one_mo { get; set; }
        public Nullable<double> three_mo { get; set; }
        public Nullable<double> six_mo { get; set; }
        public Nullable<double> one_yr { get; set; }
        public Nullable<double> two_yr { get; set; }
        public Nullable<double> three_yr { get; set; }
        public Nullable<double> five_yr { get; set; }
        public Nullable<double> seven_yr { get; set; }
        public Nullable<double> ten_yr { get; set; }
        public Nullable<double> twenty_yr { get; set; }
        public Nullable<double> thirty_yr { get; set; }
    }
}
